name       : squashfs-tools
version    : 4.5.1
release    : 14
source     :
    - https://github.com/plougher/squashfs-tools/archive/refs/tags/4.5.1.tar.gz : 277b6e7f75a4a57f72191295ae62766a10d627a4f5e5f19eadfbc861378deea7
homepage   : https://sourceforge.net/projects/squashfs
license    : GPL-2.0-or-later
component  : system.utils
summary    : Set of tools which creates squashfs filesystem
description: |
    Set of tools which creates squashfs filesystem
optimize   : speed
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - pkgconfig(lzo2)
build      : |
    %make -C squashfs-tools LZ4_SUPPORT=1 LZO_SUPPORT=1 LZMA_XZ_SUPPORT=1 XZ_SUPPORT=1 ZSTD_SUPPORT=1
install    : |
    install -Dm00755 squashfs-tools/mksquashfs $installdir/usr/bin/mksquashfs
    install -m00755 squashfs-tools/unsquashfs $installdir/usr/bin/unsquashfs
    ln -s mksquashfs $installdir/usr/bin/sqfstar
    ln -s unsquashfs $installdir/usr/bin/sqfscat

    # install manpages
    install -Dm00644 manpages/*.1 -t $installdir/usr/share/man/man1
