name        : squashfs-tools
version     : 4.3
release     : 4
source      :
    - https://sourceforge.net/projects/squashfs/files/squashfs/squashfs4.3/squashfs4.3.tar.gz : 0d605512437b1eb800b4736791559295ee5f60177e102e4d4ccd0ee241a5f3f6
homepage    : http://sourceforge.net/projects/squashfs
license     :
    - GPL-2.0
summary     : Set of tools which creates squashfs filesystem
builddeps   :
    - lz4-devel
optimize    : speed
description : |
    Set of tools which creates squashfs filesystem
build      : |
    %make -C squashfs-tools LZMA_XZ_SUPPORT=1 XZ_SUPPORT=1 LZ4_SUPPORT=1
install    : |
    install -D -m 00755 squashfs-tools/mksquashfs $installdir/usr/bin/mksquashfs
    install -D -m 00755 squashfs-tools/unsquashfs $installdir/usr/bin/unsquashfs
    install -D -m 00644 COPYING $installdir/usr/share/doc/squashfs-tools/COPYING
