name       : squashfs-tools
version    : '4.4'
release    : 9
source     :
    - https://sourceforge.net/projects/squashfs/files/squashfs/squashfs4.4/squashfs4.4.tar.gz : a981b3f3f2054b5a2e658851a3c06a2460ad04a9a8a645e0afe063a63fdbb07e
homepage   : https://sourceforge.net/projects/squashfs
license    : GPL-2.0-or-later
component  : system.utils
summary    : Set of tools which creates squashfs filesystem
description: |
    Set of tools which creates squashfs filesystem
optimize   : speed
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - pkgconfig(lzo2)
setup      : |
    %patch -p1 < $pkgfiles/fix-build-failure-against-gcc-10.patch
build      : |
    %make -C squashfs-tools LZ4_SUPPORT=1 LZO_SUPPORT=1 LZMA_XZ_SUPPORT=1 XZ_SUPPORT=1 ZSTD_SUPPORT=1
install    : |
    install -Dm00755 squashfs-tools/mksquashfs $installdir/usr/bin/mksquashfs
    install -m00755 squashfs-tools/unsquashfs $installdir/usr/bin/unsquashfs
